import { createSlice, createAsyncThunk, type PayloadAction } from '@reduxjs/toolkit';
import api from '../services/api';
import { type Subject } from '../data/types';

// The new Thunk to fetch Syllabus from your backend!
export const fetchSyllabus = createAsyncThunk('subjects/fetchSyllabus', async () => {
  const response = await api.get('/syllabus');
  return response.data;
});

const initialState: { subjects: Subject[], status: 'idle' | 'loading' | 'succeeded' | 'failed' } = {
  subjects: [],
  status: 'idle',
};

export const subjectsSlice = createSlice({
  name: 'subjects',
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder
      .addCase(fetchSyllabus.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchSyllabus.fulfilled, (state, action) => {
        state.status = 'succeeded';
        state.subjects = action.payload;
      });
  }
});

// 1. Export the actions generated by createSlice
export const { updateChapterProgress, toggleBookmark } = subjectsSlice.actions;

// 2. Export the default reducer
export default subjectsSlice.reducer;